=== andrea1192/lweb-grp/html/schemas/movies.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:element name="movies">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="movie" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="movie">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="title" type="xsd:string" />
				<xsd:element name="year" type="xsd:integer" />
				<xsd:element name="duration" type="xsd:integer" />
				<xsd:element name="summary" type="xsd:string" />
				<xsd:element name="director" type="xsd:string" />
				<xsd:element name="writer" type="xsd:string" />
			</xsd:sequence>
			<xsd:attribute use="required" name="id" type="xsd:ID" />
		</xsd:complexType>
	</xsd:element>

</xsd:schema>

=== andrea1192/lweb-grp/html/static/movies.xml
<?xml version="1.0" encoding="UTF-8"?>
<movies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="movies.xsd">

	<movie id="m1">
		<title>The Martian</title>
		<year>2015</year>
		<duration>141</duration>
		<summary>During a manned mission to Mars, Astronaut Mark Watney is presumed dead after a fierce storm and left behind by his crew. But Watney has survived and finds himself stranded and alone on the hostile planet. With only meager supplies, he must draw upon his ingenuity, wit and spirit to subsist and find a way to signal to Earth that he is alive.</summary>
		<director>Ridley Scott</director>
		<writer>Andy Weir</writer>
	</movie>

	<movie id="m2">
		<title>The Secret Life of Walter Mitty</title>
		<year>2013</year>
		<duration>114</duration>
		<summary>A timid magazine photo manager who lives life vicariously through daydreams embarks on a true-life adventure when a negative goes missing.</summary>
		<director>Ben Stiller</director>
		<writer>James Thurber</writer>
	</movie>

</movies>
