=== andrea1192/lweb-grp/html/schemas/reports.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:include schemaLocation="groups.xsd" />

	<xsd:element name="reports">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="report" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="report">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="message" type="xsd:string" minOccurs="0" />
				<xsd:element name="response" type="xsd:string" minOccurs="0" />
			</xsd:sequence>
			<xsd:attributeGroup ref="reactionAttr" />
			<xsd:attribute use="required" name="date" type="xsd:dateTime" />
			<xsd:attribute use="required" name="status">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="open" />
						<xsd:enumeration value="closed" />
						<xsd:enumeration value="accepted" />
						<xsd:enumeration value="rejected" />
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>
		</xsd:complexType>
	</xsd:element>

</xsd:schema>

=== andrea1192/lweb-grp/html/static/reports.xml
<?xml version="1.0" encoding="UTF-8"?>
<reports xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="reports.xsd">

	<report post="s1" author="baz" date="2020-01-01T00:00:00" status="closed">
		<response>No violations found</response>
	</report>
	<report post="r2" author="bar" date="2020-01-01T00:00:00" status="accepted">
		<message>Spam</message>
		<response>Post removed</response>
	</report>
	<report post="q2" author="bar" date="2020-01-01T00:00:00" status="open">
		<message>Really?</message>
	</report>
	
</reports>
